<a href="https://colab.research.google.com/github/Developers-07/Python/blob/main/Python(LabTask_03).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##**Dictionary**

In [ ]:
a1=["Google","Microsoft","Amazon"]
a2=["Sumsung","Walton","Apple"]
dic={
    "company":a1,
     "brand":a2
}
print(dic)

{'company': ['Google', 'Microsoft', 'Amazon'], 'brand': ['Sumsung', 'Walton', 'Apple']}


In [ ]:
import pandas as pd
a1=["Google","Microsoft","Amazon"]
a2=["Sumsung","Walton","Apple"]
dic={
    "company":a1,
     "brand":a2
}
df=pd.DataFrame(dic)
df

company    brand
0     Google  Sumsung
1  Microsoft   Walton
2     Amazon    Apple

In [ ]:
dc={}
for i in range(3):
  k=int(input())
  arr=[]
  for j in range(3):
    e=int(input())
    arr.append(e)
  dc[k]=arr
print(dc)


1
3
9
5
2
4
8
6
3
0
1
7
{1: [3, 9, 5], 2: [4, 8, 6], 3: [0, 1, 7]}


In [ ]:
import pandas as pd

df=pd.DataFrame(dc)
print(df)

   1  2  3
0  3  4  0
1  9  8  1
2  5  6  7


## Numpy and Pandas

In [ ]:
import numpy as np

In [ ]:
import numpy as np
my_list=[1,2,3,4,5]
arr=np.array(my_list)
print(arr)

[1 2 3 4 5]


In [ ]:
type(arr)

numpy.ndarray

In [ ]:
l1=[1,2,3,4]
l2=[4,5,6,7]
l3=[8,9,10,11]
arr=np.array([l1,l2,l3])
print(arr)
print()
print(arr.shape)

[[ 1  2  3  4]
 [ 4  5  6  7]
 [ 8  9 10 11]]

(3, 4)


In [ ]:
arr[0:,2:]

array([[ 3,  4],
       [ 6,  7],
       [10, 11]])

In [ ]:
ar1=[1,2,3,4,5,6]
nar=np.array(ar1)
nar[3:]=100
print(nar)

[  1   2   3 100 100 100]


In [ ]:
ar1=np.arange(0,10).reshape(5,2)
ar2=np.arange(11,21).reshape(5,2)
ar3=ar1*ar2
ar3

array([[  0,  12],
       [ 26,  42],
       [ 60,  80],
       [102, 126],
       [152, 180]])

In [ ]:
np.zeros((4,5),dtype=int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [ ]:
np.random.rand(4,5)

array([[0.74351547, 0.42163231, 0.60757101, 0.6744969 , 0.48655762],
       [0.88985456, 0.04761349, 0.6049789 , 0.29439062, 0.10221397],
       [0.51084359, 0.34427   , 0.64279798, 0.9829043 , 0.24889409],
       [0.10336392, 0.3128957 , 0.0976152 , 0.41325898, 0.44155193]])

In [ ]:
df=pd.read_csv("/content/lab_label (1).txt")
df

District  Size  Population      Speciality
0         Dhaka  1432     2250000  Administrative
1       Gazipur   879      567984        Industry
2   Narayanganj   576       53426        Industry
3       Rajbari   897       65899     Agriculture
4    Chittagong  1234     1345566        Industry
5   Cox's Bazer   456       46567         Tourist
6     Bandarban   345       67579         Tourist
7       Khustia   432       57798        Business
8          Feni   543       67890     Agriculture
9       Comilla   564       77898         Tourist
10      Barisal   577       89750     Agriculture
11     Faridpur   567       77650     Agriculture
12      Rangpur   575       78966     Agriculture
13      Chadpur   876       67789         Tourist

In [ ]:
df.head(8)

District  Size  Population      Speciality
0        Dhaka  1432     2250000  Administrative
1      Gazipur   879      567984        Industry
2  Narayanganj   576       53426        Industry
3      Rajbari   897       65899     Agriculture
4   Chittagong  1234     1345566        Industry
5  Cox's Bazer   456       46567         Tourist
6    Bandarban   345       67579         Tourist
7      Khustia   432       57798        Business

In [ ]:
df.dtypes

District      object
Size           int64
Population     int64
Speciality    object
dtype: object

In [ ]:
df.describe()

Size    Population
count    14.000000  1.400000e+01
mean    710.928571  3.510544e+05
std     314.457155  6.518123e+05
min     345.000000  4.656700e+04
25%     548.250000  6.631900e+04
50%     575.500000  7.277000e+04
75%     878.250000  8.705400e+04
max    1432.000000  2.250000e+06

In [ ]:
df.isnull().sum()

District      0
Size          0
Population    0
Speciality    0
dtype: int64